### ISSUE TITLE
Noticed once you click Login or Register Button on Branch Develop it forces close, hence Restart App.

### ISSUE THREAD

**Issue by Madonahs** [Madonahs/GrowWithGoogleTeamProject#48]
Hey please try clicking the button login and register on develop without registering , it should not collapse but ask a user to register or login in. 

 at com.madonasyombua.growwithgoogleteamproject.database.AppLoginManager.signinUser(AppLoginManager.java:43)                                                                                               at com.madonasyombua.growwithgoogleteamproject.ui.fragment.LoginFragment$1.onClick(LoginFragment.java:46)

**Comment by MaherSoua** [comment]
fixed with 72d66b9

**Comment by MaherSoua** [comment]
fixed with 72d66b9
